# see https://github.com/cncf/clomonitor/blob/main/docs/checks.md#exemptions
exemptions:
  - check: artifacthub_badge
    reason: "Artifact Hub doesn't support Android packages"
  - check: openssf_badge
    reason: "ETOOMANYBADGES, but the work has been done: https://www.bestpractices.dev/projects/10007"
