/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.agent.session

import io.opentelemetry.android.Incubating
import io.opentelemetry.android.session.Session
import java.io.File

/**
 * Storage for sessions written by the agent's built-in session manager.
 *
 * By default the manager does not read or write storage during construction. It saves each newly generated
 * session, starting on the first session access. This replaces any previously stored session.
 * With `linkPreviousSessionOnRestart` enabled, initialization reads [get] once to link the first
 * new session to the saved ID. It never resumes that session. Supplying storage alone does not
 * enable restart linking.
 *
 * Calls run synchronously on the calling thread, including during SDK initialization and
 * telemetry recording. Implementations must be thread-safe, return promptly, and handle their
 * own failures without throwing. Saves and observer notifications run in order without holding
 * the manager's lock. Concurrent reads return the current session while those calls run; another
 * session change is deferred until they finish and a subsequent access detects expiry.
 * The manager does not provide a storage fallback or manage storage cleanup.
 */
@Incubating
interface SessionStorage {
    /** Returns the stored session, or a session with an empty ID when no record is available. */
    fun get(): Session

    /** Saves [newSession] after it is generated by the manager. */
    fun save(newSession: Session)

    companion object {
        /**
         * Stores the agent's generated session IDs in a versioned, atomically replaced file.
         * Use a file in the app's no-backup directory, owned by one SDK instance in one process.
         * Other processes must use different files. This does not provide cross-process locking.
         * Reads and writes are synchronous. I/O failures retain an in-memory session, but can lose
         * the next launch's link. Unsupported record versions are left untouched.
         */
        @JvmStatic
        fun file(file: File): SessionStorage = FileSessionStorage(file)
    }
}
