/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.agent.session

import io.opentelemetry.android.Incubating
import io.opentelemetry.android.session.Session

/**
 * Storage for sessions written by the agent's built-in session manager.
 *
 * The manager does not read or write storage during construction. It saves each newly generated
 * session, starting on the first session access. This replaces any previously stored session.
 * It does not call [get] to restore a session, so supplying persistent storage alone does not
 * enable session restoration.
 *
 * Calls run synchronously on the calling thread, including during SDK initialization and
 * telemetry recording. Implementations must be thread-safe, return promptly, and handle their
 * own failures without throwing. Saves and observer notifications run in order without holding
 * the manager's lock. Concurrent reads return the current session while those calls run; another
 * session change is deferred until they finish and a subsequent access detects expiry.
 * The manager does not provide a storage fallback or manage storage cleanup.
 */
@Incubating
interface SessionStorage {
    /** Returns the session held by this storage. The built-in manager does not currently read it. */
    fun get(): Session

    /** Saves [newSession] after it is generated by the manager. */
    fun save(newSession: Session)
}
