services:
  collector:
    image: "otel/opentelemetry-collector-contrib:0.159.0@sha256:1f2c54a30e713fac6b3ae77a1ec84010c2007e29ced8ec666214fc2f6739c1cc"
    volumes:
      - ./collector.yaml:/etc/demo-collector.yaml
    entrypoint: ["/otelcol-contrib"]
    command: ["--config", "/etc/demo-collector.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  jaeger:
    image: "jaegertracing/jaeger:2.20.0@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8"
    ports:
      - "16686:16686" # UI
