services:
  collector:
    image: "otel/opentelemetry-collector-contrib:0.156.0@sha256:125bdbeb7590cc1952c5b3430ecf14063568980c2c93d5b38676cc0446ed8108"
    volumes:
      - ./collector.yaml:/etc/demo-collector.yaml
    entrypoint: ["/otelcol-contrib"]
    command: ["--config", "/etc/demo-collector.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  jaeger:
    image: "jaegertracing/jaeger:2.19.0@sha256:ede4864215be4cd85bd8c3129a2fea6c5713c5653c7282c429dba123014bc68b"
    ports:
      - "16686:16686" # UI
