services:
  collector:
    image: "otel/opentelemetry-collector-contrib:0.158.0@sha256:c5918f78992ee73b0d6f0e599423ac5ec52dd5d9726733114d6eca53d5a32ed5"
    volumes:
      - ./collector.yaml:/etc/demo-collector.yaml
    entrypoint: ["/otelcol-contrib"]
    command: ["--config", "/etc/demo-collector.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
  jaeger:
    image: "jaegertracing/jaeger:2.20.0@sha256:46a886260e04002d8f45e213fc39063fa11a50446048fdaa64786fc0840cb9f8"
    ports:
      - "16686:16686" # UI
