/*
 * Copyright Splunk Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.splunk.rum;

import io.opentelemetry.api.common.Attributes;

/**
 * Configuration class for the Splunk Android RUM (Real User Monitoring) library.
 * <p>
 * Both the beaconUrl and the rumAuthToken are mandatory configuration settings. Trying
 * to build a Config instance without both of these items specified will result in an exception being thrown.
 */
public class Config {

    private final String beaconUrl;
    private final String rumAuthToken;
    private final boolean debugEnabled;
    private final String applicationName;
    private final boolean crashReportingEnabled;
    private final Attributes globalAttributes;
    private final boolean networkMonitorEnabled;
    private final boolean anrDetectionEnabled;

    private Config(Builder builder) {
        this.beaconUrl = builder.beaconUrl;
        this.rumAuthToken = builder.rumAuthToken;
        this.debugEnabled = builder.debugEnabled;
        this.applicationName = builder.applicationName;
        this.crashReportingEnabled = builder.crashReportingEnabled;
        this.globalAttributes = builder.globalAttributes;
        this.networkMonitorEnabled = builder.networkMonitorEnabled;
        this.anrDetectionEnabled = builder.anrDetectionEnabled;
    }

    /**
     * The configured "beacon" URL for the RUM library.
     */
    public String getBeaconUrl() {
        return beaconUrl;
    }

    /**
     * The configured RUM auth token for the library.
     */
    public String getRumAuthToken() {
        return rumAuthToken;
    }

    /**
     * Is debug mode enabled.
     */
    public boolean isDebugEnabled() {
        return debugEnabled;
    }

    /**
     * The name under which this application will be reported to the Splunk RUM system.
     */
    public String getApplicationName() {
        return applicationName;
    }

    /**
     * Is the crash-reporting feature enabled or not.
     */
    public boolean isCrashReportingEnabled() {
        return crashReportingEnabled;
    }

    /**
     * The set of {@link Attributes} which will be applied to every span generated by the RUM
     * instrumentation.
     */
    public Attributes getGlobalAttributes() {
        return globalAttributes;
    }

    /**
     * Create a new instance of the {@link Builder} class. All default configuration options will be pre-populated.
     */
    public static Builder builder() {
        return new Builder();
    }

    public boolean isNetworkMonitorEnabled() {
        return networkMonitorEnabled;
    }

    public boolean isAnrDetectionEnabled() {
        return anrDetectionEnabled;
    }

    /**
     * Builder class for the Splunk RUM {@link Config} class.
     */
    public static class Builder {
        public boolean networkMonitorEnabled = true;
        public boolean anrDetectionEnabled = true;
        private String beaconUrl;
        private String rumAuthToken;
        private boolean debugEnabled = false;
        private String applicationName;
        private boolean crashReportingEnabled = true;
        private Attributes globalAttributes = Attributes.empty();

        /**
         * Create a new instance of {@link Config} from the options provided.
         */
        public Config build() {
            if (rumAuthToken == null || beaconUrl == null || applicationName == null) {
                throw new IllegalStateException("You must provide a rumAuthToken, a beaconUrl, and an application name to create a valid Config instance.");
            }
            return new Config(this);
        }

        /**
         * Assign the "beacon" URL to be used by the RUM library.
         *
         * @return this
         */
        public Builder beaconUrl(String beaconUrl) {
            this.beaconUrl = beaconUrl;
            return this;
        }

        /**
         * Assign the RUM auth token to be used by the RUM library.
         *
         * @return this
         */
        public Builder rumAuthToken(String rumAuthToken) {
            this.rumAuthToken = rumAuthToken;
            return this;
        }

        /**
         * Enable/disable debugging information to be emitted from the RUM library. This is set to
         * {@code false} by default.
         *
         * @return this
         */
        public Builder debugEnabled(boolean enable) {
            this.debugEnabled = enable;
            return this;
        }

        /**
         * Enable/disable the crash reporting feature. Enabled by default.
         *
         * @return this
         */
        public Builder crashReportingEnabled(boolean enable) {
            this.crashReportingEnabled = enable;
            return this;
        }

        /**
         * Enable/disable the network monitoring feature. Enabled by default.
         *
         * @return this
         */
        public Builder networkMonitorEnabled(boolean enable) {
            this.networkMonitorEnabled = enable;
            return this;
        }

        /**
         * Assign an application name that will be used to identify your application in the Splunk RUM UI.
         *
         * @return this.
         */
        public Builder applicationName(String applicationName) {
            this.applicationName = applicationName;
            return this;
        }

        /**
         * Enable/disable the ANR detection feature. Enabled by default. If enabled, if the main
         * thread is unresponsive for 5s or more, an event including the main thread's stack trace will be
         * reported to the RUM system.
         *
         * @return this.
         */
        public Builder anrDetectionEnabled(boolean enable) {
            this.anrDetectionEnabled = enable;
            return this;
        }

        /**
         * Provide a set of global {@link Attributes} that will be applied to every span generated
         * by the RUM instrumentation.
         *
         * @return this.
         */
        public Builder globalAttributes(Attributes attributes) {
            this.globalAttributes = attributes == null ? Attributes.empty() : attributes;
            return this;
        }
    }
}
