/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.instrumentation

import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.gradle.api.GradleException
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Path
import kotlin.io.path.createFile
import kotlin.io.path.writeText

class TelemetryDocsMergerTest {
    @TempDir
    lateinit var temporaryDirectory: Path

    @Test
    fun `merges observations into deterministic version one yaml`() {
        val firstObservation =
            temporaryDirectory
                .resolve("first.telemetry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {"signals":[
                          {"type":"event","name":"toy.event","scope":"toy.scope","attributes":[
                            {"name":"toy.required","type":"string","value":"secret"}
                          ]},
                          {"type":"event","name":"z.event","scope":"toy.scope","attributes":[]},
                          {"type":"span","name":"ignored","scope":"another.scope","span_kind":"internal","attributes":[]}
                        ]}
                        """.trimIndent(),
                    )
                }
        val secondObservation =
            temporaryDirectory
                .resolve("second.telemetry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {"signals":[
                          {"type":"event","name":"toy.event","scope":"toy.scope","attributes":[
                            {"name":"toy.upstream","type":"int"},
                            {"name":"toy.extra","type":"boolean"}
                          ]},
                          {"type":"event","name":"a.event","scope":"toy.scope","attributes":[]},
                          {"type":"metric","name":"toy.metric","scope":"toy.scope","instrument":"counter","unit":"request","attributes":[]}
                        ]}
                        """.trimIndent(),
                    )
                }
        val registry =
            temporaryDirectory
                .resolve("registry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {
                          "groups": [{
                            "id": "event.toy",
                            "type": "event",
                            "name": "toy.event",
                            "attributes": [
                              {"name": "toy.required", "requirement_level": "required"},
                              {"name": "toy.upstream", "requirement_level": "recommended"},
                              {"name": "toy.optional", "requirement_level": "opt_in"}
                            ],
                            "lineage": {"attributes": {
                              "toy.required": {"source_group": "registry.android.semconv"},
                              "toy.upstream": {"source_group": "registry.toy"},
                              "toy.optional": {"source_group": "registry.toy"}
                            }}
                          }]
                        }
                        """.trimIndent(),
                    )
                }
        val localRegistry =
            temporaryDirectory
                .resolve("events.yaml")
                .createFile()
                .apply { writeText("groups:\n  - id: event.toy\n") }
        val output = temporaryDirectory.resolve("telemetry.yaml").toFile()

        TelemetryDocsMerger.merge(
            moduleName = "toy-module",
            scopeNames = listOf("toy.scope"),
            observationFiles = setOf(secondObservation.toFile(), firstObservation.toFile()),
            resolvedRegistryFile = registry.toFile(),
            localRegistryFile = localRegistry.toFile(),
            outputFile = output,
        )

        assertThat(output).hasContent(
            """
            # GENERATED FILE - do not edit. Regenerated by :mergeAllTelemetryDocs.
            schema_version: 1
            module: "toy-module"
            scopes:
              - "toy.scope"
            signals:
              - type: event
                name: "a.event"
                scope: "toy.scope"
                registry_id: null
                attributes: []
              - type: event
                name: "z.event"
                scope: "toy.scope"
                registry_id: null
                attributes: []
              - type: event
                name: "toy.event"
                scope: "toy.scope"
                registry_id: "event.toy"
                attributes:
                  - name: "toy.extra"
                    type: boolean
                    registry: none
                  - name: "toy.required"
                    type: string
                    registry: local
                  - name: "toy.upstream"
                    type: int
                    registry: upstream

            """.trimIndent(),
        )
        assertThat(output.readText()).doesNotContain("secret", "toy.metric")
    }

    @Test
    fun `identifies a unique span registry group and marks ambiguous spans unidentified`() {
        val observation =
            temporaryDirectory
                .resolve("spans.telemetry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {"signals":[
                          {"type":"span","name":"GET","scope":"http.scope","span_kind":"client","attributes":[
                            {"name":"http.request.method","type":"string"},
                            {"name":"server.address","type":"string"}
                          ]},
                          {"type":"span","name":"operation","scope":"ambiguous.scope","span_kind":"internal","attributes":[
                            {"name":"code.function.name","type":"string"}
                          ]}
                        ]}
                        """.trimIndent(),
                    )
                }
        val registry =
            temporaryDirectory
                .resolve("span-registry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {"groups":[
                          {"id":"span.http.client","type":"span","span_kind":"client","attributes":[
                            {"name":"http.request.method","requirement_level":"required"},
                            {"name":"server.address","requirement_level":"required"}
                          ]},
                          {"id":"span.rpc.client","type":"span","span_kind":"client","attributes":[
                            {"name":"rpc.system","requirement_level":"required"}
                          ]},
                          {"id":"span.internal.first","type":"span","span_kind":"internal","attributes":[
                            {"name":"code.function.name","requirement_level":"required"}
                          ]},
                          {"id":"span.internal.second","type":"span","span_kind":"internal","attributes":[
                            {"name":"code.function.name","requirement_level":"required"}
                          ]}
                        ]}
                        """.trimIndent(),
                    )
                }
        val localRegistry =
            temporaryDirectory
                .resolve("empty-events.yaml")
                .createFile()
                .apply { writeText("groups: []\n") }
        val output = temporaryDirectory.resolve("span-telemetry.yaml").toFile()

        TelemetryDocsMerger.merge(
            moduleName = "span-module",
            scopeNames = listOf("http.scope", "ambiguous.scope"),
            observationFiles = setOf(observation.toFile()),
            resolvedRegistryFile = registry.toFile(),
            localRegistryFile = localRegistry.toFile(),
            outputFile = output,
        )

        assertThat(output.readText())
            .contains(
                """registry_id: "span.http.client"""",
                """registry_id: "unidentified"""",
            ).doesNotContain(
                """name: "GET"""",
                """name: "operation"""",
            )
    }

    @Test
    fun `fails when a non opt-in local registry attribute was not observed`() {
        val observation =
            temporaryDirectory
                .resolve("observation.telemetry.json")
                .createFile()
                .apply {
                    writeText(
                        """{"signals":[{"type":"event","name":"toy.event","scope":"toy.scope","attributes":[]}]}""",
                    )
                }
        val registry =
            temporaryDirectory
                .resolve("registry.json")
                .createFile()
                .apply {
                    writeText(
                        """
                        {"groups":[{
                          "id":"event.toy",
                          "type":"event",
                          "name":"toy.event",
                          "attributes":[{"name":"toy.required","requirement_level":"required"}]
                        }]}
                        """.trimIndent(),
                    )
                }
        val localRegistry =
            temporaryDirectory
                .resolve("events.yaml")
                .createFile()
                .apply { writeText("groups:\n  - id: event.toy\n") }

        assertThatThrownBy {
            TelemetryDocsMerger.merge(
                moduleName = "toy-module",
                scopeNames = listOf("toy.scope"),
                observationFiles = setOf(observation.toFile()),
                resolvedRegistryFile = registry.toFile(),
                localRegistryFile = localRegistry.toFile(),
                outputFile = temporaryDirectory.resolve("telemetry.yaml").toFile(),
            )
        }.isInstanceOf(GradleException::class.java)
            .hasMessageContaining("toy-module")
            .hasMessageContaining("toy.event")
            .hasMessageContaining("toy.required")
    }
}
