/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'activity'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ActivityAttributes {
    /**
     * <p>The Android activity class name for which telemetry is relevant.</p>
     */
    const val ACTIVITY_NAME: String = "activity.name"
}