

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'android'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object AndroidAttributes {


    /**
    * <p>The Android log tag supplied to android.util.Log.</p>
    */

    const val ANDROID_LOG_TAG: String = "android.log.tag"

}