

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'battery'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object BatteryAttributes {


    /**
    * <p>The current battery charge as a percentage of total capacity.</p>
    */
    const val BATTERY_PERCENT: String = "battery.percent"

}