

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'fragment'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object FragmentAttributes {


    /**
    * <p>The Android fragment class name for which telemetry is relevant.</p>
    */

    const val FRAGMENT_NAME: String = "fragment.name"

}