/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'heap'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object HeapAttributes {
    /**
     * <p>The amount of free heap memory, in bytes.</p>
     */
    const val HEAP_FREE: String = "heap.free"
}