

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'hw'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object HwAttributes {


    /**
    * <p>The hardware pointer button associated with a pointer gesture.</p>
    */

    const val HW_POINTER_BUTTON: String = "hw.pointer.button"


    /**
    * <p>The click count associated with a pointer gesture.</p>
    */

    const val HW_POINTER_CLICKS: String = "hw.pointer.clicks"


    /**
    * <p>The hardware pointer type associated with a pointer gesture.</p>
    */

    const val HW_POINTER_TYPE: String = "hw.pointer.type"

}