

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'last'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object LastAttributes {


    /**
    * <p>The previously visible screen name.</p>
    */
    const val LAST_SCREEN_NAME: String = "last.screen.name"

}