

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'network'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object NetworkAttributes {


    /**
    * <p>The Android network status after a network change.</p>
    */

    const val NETWORK_STATUS: String = "network.status"

}