

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'screen'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object ScreenAttributes {


    /**
    * <p>The current application screen name used by the Android SDK.</p>
    */

    const val SCREEN_NAME: String = "screen.name"


    /**
    * <p>The Android screen orientation.</p>
    */

    const val SCREEN_ORIENTATION: String = "screen.orientation"

}