/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'span'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object SpanAttributes {
    /**
     * <p>A string representation of the span exporter configured during SDK initialization.</p>
     */
    const val SPAN_EXPORTER: String = "span.exporter"
}
