

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'start'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object StartAttributes {


    /**
    * <p>The application start type.</p>
    */

    const val START_TYPE: String = "start.type"

}