/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'storage'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object StorageAttributes {


    /**
     * <p>The amount of free application file storage, in bytes.</p>
     */
    const val STORAGE_FREE: String = "storage.free"

}