

package io.opentelemetry.android.semconv

/**
 * Autogenerated OpenTelemetry Android semantic conventions for 'websocket'.
 *
 * DO NOT EDIT - AUTOGENERATED FILE
 */
@Suppress("unused")
object WebsocketAttributes {


    /**
    * <p>The size of a WebSocket message payload.</p>
    */

    const val WEBSOCKET_MESSAGE_SIZE: String = "websocket.message.size"


    /**
    * <p>The WebSocket message payload type.</p>
    */

    const val WEBSOCKET_MESSAGE_TYPE: String = "websocket.message.type"

}