name: Draft CHANGELOG entries for a release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Run changelog draft script
        run: ./.github/scripts/draft-change-log-entries.sh
