name: Issue management - remove labels as needed

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  issue_comment:
    permissions:
      contents: read
      issues: write
    if: >
      contains(github.event.issue.labels.*.name, 'needs author feedback') &&
      github.event.comment.user.login == github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Remove labels
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit --remove-label "needs author feedback" $ISSUE_NUMBER
          gh issue edit --remove-label "stale" $ISSUE_NUMBER