name: Reusable - Markdown link check

on:
  workflow_call:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install markdown-link-check
        # https://github.com/tcort/markdown-link-check/issues/297
        run: npm install -g markdown-link-check@3.11.2

      - name: Run markdown-link-check
        run: |
          find . -type f \
                 -name '*.md' \
                 -not -path './CHANGELOG.md' \
               | xargs .github/scripts/markdown-link-check-with-retry.sh